[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "vershachi"
version = "0.1.0"
description = "Vershachi is a Python-based toolkit designed to streamline the development of machine learning and unlearning applications."
authors = ["mo_shahab <mohdshahabuddinsoharwardi@gmail.com>"]

[tool.poetry.dependencies]
# Add your project dependencies here
python = "^3.10"
numpy = "^1.21.5"
pandas = "^1.3.5"
scikit-learn = "^1.4.1"
torch = "^1.10.1"

[tool.poetry.dev-dependencies]
# Add your development dependencies here
